train:
  _target_: torch.utils.data.ConcatDataset # we can concat datasets if we want to
  datasets:
    - _target_: src.datasets.ExampleDataset
      input_length: 1024
      dataset_length: 15
      n_classes: 10
      name: "train15"
      instance_transforms: ${transforms.instance_transforms.train}
    - _target_: src.datasets.ExampleDataset
      input_length: 1024
      dataset_length: 20
      n_classes: 10
      name: "train20"
      instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.ExampleDataset
  input_length: 1024
  dataset_length: 15
  n_classes: 10
  name: "val"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.ExampleDataset
  input_length: 1024
  dataset_length: 15
  n_classes: 10
  name: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
