train:
  _target_: src.datasets.ExampleDataset
  input_length: 1024
  dataset_length: 15
  n_classes: 10
  limit: 10
  name: "val"
val:
  _target_: src.datasets.ExampleDataset
  input_length: 1024
  dataset_length: 15
  limit: 10
  n_classes: 10
  name: "val"
