device: "auto"
audio_only: true
train: []
inference:
  - _target_: src.metrics.SiSNR
    device: ${metrics.device}
    audio_only: ${metrics.audio_only}
    name: "SI_SNR"
  - _target_: src.metrics.SiSNRi
    device: ${metrics.device}
    audio_only: ${metrics.audio_only}
    name: "SI_SNRi"
  - _target_: src.metrics.SDRi
    device: ${metrics.device}
    audio_only: ${metrics.audio_only}
    name: "SDRi"
  - _target_: src.metrics.PESQ
    device: ${metrics.device}
    audio_only: ${metrics.audio_only}
    fs: 8000
    mode: "wb"
    name: "PESQ"
  - _target_: src.metrics.STOI
    device: ${metrics.device}
    audio_only: ${metrics.audio_only}
    fs: 8000
    name: "STOI"
