_target_: src.model.ARTFSNet
num_audio_channels: 256
num_video_channels: 512
num_rtfs_blocks: 6
num_caf_blocks: 4
hidden_dim: 64
hidden_dim_rnn: 32
num_upsample_depth_rtfs: 2
num_upsample_depth_vp: 4
num_heads_caf: 4
n_fft: 256
n_freq: 64
hop_length: 128
