defaults:
  - model: artfs
  - metrics: inference_metrics
  - datasets: custom_dir_dataset
  - dataloader: one_batch
  - transforms: no_transform
  - _self_
inferencer:
  device_tensors: ["mixture", "sources", "video"]
  device: auto # device name or "auto"
  save_path: "rtfs" # any name here, can be a dataset name
  seed: 42
  from_pretrained: "saved/artfs_net.pth" # path to the pretrained model
