defaults:
  - model: convtasnet
  - metrics: inference_metrics_audio
  - datasets: audio_inference
  - dataloader: base_loader
  - transforms: no_transform
  - _self_
inferencer:
  device_tensors: ["mixture", "sources"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "saved_inference" # any name here, can be a dataset name
  seed: 42
  from_pretrained: "saved/convtasnet_100epoch/model_best.pth" # path to the pretrained model
