defaults:
  - model: rtfs
  - datasets: custom_dir_dataset
  - dataloader: one_batch
  - transforms: no_transform
  - _self_
inferencer:
  device_tensors: ["mixture", "sources", "video"]
  device: auto # device name or "auto"
  seed: 42
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
