defaults:
  - model: sepreformer
  - writer: wandb
  - metrics: train_metrics
  - datasets: audio_train
  - dataloader: base_loader
  - transforms: no_transform
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 1e-2
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 25000
loss_function:
  _target_: src.loss.MultiLoss
  alpha: 0.4
  perm_invariant: true
  clip_value: 30
  n_fft: 512
  hop_length: 128
trainer:
  log_step: 100
  n_epochs: 50
  epoch_len: 500
  device_tensors: ["mixture", "sources"] # which tensors should be on device (ex. GPU)
  max_grad_norm: 5
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: true # if True, will override the previous run with the same name
  monitor: "max val_SI-SNRi" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 42
  parallel: false
  device_ids: [2]  # default: [0]
