defaults:
  - model: artfs
  - writer: wandb
  - metrics: train_metrics
  - datasets: audio_video_train
  - dataloader: big_loader
  - transforms: no_transform
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 1e-1
lr_scheduler:
  null
lr_scheduler_plateau:
  _target_: src.scheduler.ReduceLROnPlateau
  mode: "max"
  factor: 0.5
  patience: 5
loss_function:
  _target_: src.loss.SiSNRLoss
  permutation_invariant_training: false
trainer:
  log_step: 250
  n_epochs: 500
  epoch_len: 2000
  device_tensors: ["mixture", "sources", "video"] # which tensors should be on device (ex. GPU)
  max_grad_norm: 5
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max val_SI_SNRi" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 42
  parallel: false
